# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4312f921a97a817d7327ba7256d8a9260fcf1b0027b9fbfe45dc10b4b4d556a650ae5f659c283547ea55e12784f990fb1c1592b35a44496a63abd34d0a3039fb

test:
  secret_key_base: 28723cb2a1c7a61b39421d90fe20e822b3aa9c5c844a3032f78c7b0a317058706b3702004426c984ac8d8be1186dff8b097e51c8f29f938e4036c4617d24c1ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
